apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dakera-models
  namespace: dakera
  labels:
    app.kubernetes.io/name: dakera
    app.kubernetes.io/component: models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
